### PR TITLE
Fix error when Nominatim region check was aborted.

### LINKED ISSUE #285: regionCheck frontend error / ошибка на фронтенде в regionCheck
Возникает при нажатии на карту, воспроизводится в версии 1.3.2 и в мастере.

Локация: https://github.com/PastVu/pastvu/blob/a3e79baafad1424af04cbed20cebd332e841295a/public/js/module/admin/regionCheck.js#L260
image

### PR DESCRIPTION
**Pull request by kabalin**
Also overcomes Leaflet 1.7.1 bug when Safari triggers double click event
on map.

Closes #285

### CODE REVIEW

File: public/js/module/admin/regionCheck.js [hunk 1]
```diff
@@ -187,17 +187,14 @@ define([
         updateRegionAbort: function () {
             if (this.ownRegionsDeffered) {
                 this.ownRegionsDeffered.reject();
-                this.ownRegionsDeffered = null;
```
Comment (kabalin) [inline public/js/module/admin/regionCheck.js:190]: Reason for change here - rejects will be picked by .always where variable is nulled.

File: public/js/module/admin/regionCheck.js [hunk 2]
```diff
@@ -187,17 +187,14 @@ define([
...
             }
 
             if (this.nominatimRegionsDeffered) {
                 this.nominatimRegionsDeffered.reject();
-                this.nominatimRegionsDeffered = null;
             }
 
             if (requestNominatim) {
                 requestNominatim.abort();
-                requestNominatim = null;
```
Comment (kabalin) [inline public/js/module/admin/regionCheck.js:200]: Same for ajax promise, .always callback will make it null.

**Review by klimashkin — APPROVED** [review]
